{{- if .Values.passboltEnv.secret.secretProvider.enabled }}
{{- $type := "sec" -}}
{{- $action := "env" -}}
{{- $Name := include "passbolt-library.fullname" . -}}
{{- $fullName := printf "%s-%s-%s" $Name $type $action -}}

{{- if .Capabilities.APIVersions.Has "secrets-store.csi.x-k8s.io/v1" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
{{- else }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
{{- end }}
kind: SecretProviderClass
metadata:
  name: {{ $fullName }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "passbolt-library.labels" . | nindent 4 }}
    {{- include "passbolt-library.selectorLabels" . | nindent 4 }}
    {{- include "passbolt-library.typelabels" (dict "action" $action "type" $type) | nindent 4 }}
spec:
  provider: {{ required "Specify a valid provider." .Values.passboltEnv.secret.secretProvider.provider }}
  parameters:
    {{- toYaml .Values.passboltEnv.secret.secretProvider.parameters | nindent 4 }}
  secretObjects:
  {{- with .Values.passboltEnv.secret.secretProvider.data }}
  - data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    secretName: {{ $fullName }}
    type: Opaque
{{- end }}